from __future__ import annotations

from datetime import datetime
from uuid import uuid4

from sqlalchemy.orm import Session

from app.services.report_registry.hashing import (
    compute_report_hash,
)

from app.services.report_registry.models import (
    RegisteredReport,
    ReportStatus,
    ReportType,
)

from app.services.report_registry.storage import (
    store_report,
)

from app.services.report_registry.urls import (
    build_report_verification_url,
)

from app.services.report_registry.repositories.report_registry_repository import (
    ReportRegistryRepository,
)


# ==========================================================
# Report Identifier
# ==========================================================

_PREFIX = {

    ReportType.CLAIM: "CLM",

    ReportType.ALLOCATOR: "ALC",

    ReportType.INVESTIGATION: "INV",

    ReportType.EXECUTIVE: "EXE",

}


def generate_report_id(
    report_type: ReportType,
) -> str:
    """
    Generates a globally unique report identifier.
    """

    return (

        f"{_PREFIX[report_type]}-"

        f"{datetime.utcnow():%Y%m%d}-"

        f"{uuid4().hex[:8].upper()}"

    )


# ==========================================================
# Registry
# ==========================================================

def register_report(
    *,
    db: Session,
    report_type: ReportType,
    workspace_id: int,
    file_name: str,
    pdf_bytes: bytes,
    metadata: dict | None = None,
) -> RegisteredReport:
    """
    Canonical institutional report registration.

    Every institutional PDF generated by TTL
    should pass through this function.
    """

    #
    # Identity
    #

    report_id = generate_report_id(
        report_type,
    )

    #
    # Fingerprint
    #

    fingerprint = compute_report_hash(
        pdf_bytes,
    )

    #
    # Storage
    #

    stored = store_report(

        report_id=report_id,

        file_name=file_name,

        pdf_bytes=pdf_bytes,

    )

    #
    # Verification URL
    #

    verification_url = (

        build_report_verification_url(

            report_id=report_id,

        )

    )

    #
    # Domain model
    #

    registered = RegisteredReport(

        report_id=report_id,

        report_type=report_type,

        workspace_id=workspace_id,

        generated_at=datetime.utcnow(),

        status=ReportStatus.GENERATED,

        verification_url=verification_url,

        storage_key=stored.storage_key,

        file_name=stored.file_name,

        sha256=fingerprint.sha256,

        file_size=fingerprint.file_size,

        metadata=metadata or {},

    )

    #
    # Persist
    #

    repository = ReportRegistryRepository(
        db,
    )

    repository.create(
        registered,
    )

    return registered