from __future__ import annotations

from datetime import datetime

from sqlalchemy.orm import Session

from app.services.report_registry.hashing import (
    compute_report_hash,
)

from app.services.report_registry.models import (
    RegisteredReport,
    ReportStatus,
    ReportType,
)

from app.services.report_registry.registry import (
    generate_report_id,
)

from app.services.report_registry.repositories.report_registry_repository import (
    ReportRegistryRepository,
)

from app.services.report_registry.storage import (
    store_report,
)

from app.services.report_registry.urls import (
    build_report_verification_url,
)


# ==========================================================
# Report Registry Service
# ==========================================================

class ReportRegistryService:
    """
    Canonical service responsible for registering every
    institutional report generated by Trading Truth Layer.

    Responsibilities

        • Generate report identifiers

        • Compute report fingerprints

        • Store immutable PDF artifacts

        • Generate verification URLs

        • Persist registry metadata

    Every PDF generator should consume this service.
    """

    def __init__(
        self,
        db: Session,
    ) -> None:

        self.db = db

        self.repository = ReportRegistryRepository(
            db,
        )


    # ======================================================
    # Reservation
    # ======================================================

    def reserve_report(
        self,
        *,
        report_type: ReportType,
        workspace_id: int,
    ) -> RegisteredReport:
        """
        Reserves a report identity before the PDF is rendered.

        This allows the PDF to embed its permanent verification
        URL and QR code during the initial render.
        """

        report_id = generate_report_id(
            report_type,
        )

        verification_url = build_report_verification_url(
            report_id=report_id,
        )

        return RegisteredReport(

            report_id=report_id,

            report_type=report_type,

            workspace_id=workspace_id,

            generated_at=datetime.utcnow(),

            status=ReportStatus.RESERVED,

            verification_url=verification_url,

            storage_key="",

            file_name="",

            sha256="",

            file_size=0,

            metadata={},

        )

    # ======================================================
    # Finalization
    # ======================================================

    def finalize_report(
        self,
        *,
        reserved_report: RegisteredReport,
        report_title: str,
        file_name: str,
        pdf_bytes: bytes,
        claim_id: int | None = None,
        generated_by: int | None = None,
        report_version: str = "1.0",
        metadata: dict | None = None,
    ) -> RegisteredReport:
        """
        Finalizes a reserved report after the PDF
        has been successfully rendered.
        """

        fingerprint = compute_report_hash(
            pdf_bytes,
        )

        stored = store_report(

            report_id=reserved_report.report_id,

            file_name=file_name,

            pdf_bytes=pdf_bytes,

        )

        reserved_report.storage_key = stored.storage_key

        reserved_report.file_name = stored.file_name

        reserved_report.sha256 = fingerprint.sha256

        reserved_report.file_size = fingerprint.file_size

        reserved_report.metadata = metadata or {}

        reserved_report.status = (
            ReportStatus.GENERATED
        )

        self.repository.create(

            report=reserved_report,

            report_title=report_title,

            report_version=report_version,

            claim_id=claim_id,

            generated_by=generated_by,

        )

        return reserved_report

    # ======================================================
    # Lookup
    # ======================================================

    def get_report(
        self,
        report_id: str,
    ):

        return self.repository.get_by_report_id(
            report_id,
        )

    def get_workspace_reports(
        self,
        workspace_id: int,
    ):

        return self.repository.get_workspace_reports(
            workspace_id,
        )

    # ======================================================
    # Lifecycle
    # ======================================================

    def revoke_report(
        self,
        report_id: str,
    ) -> None:

        self.repository.mark_revoked(
            report_id,
        )

    def verify_report(
        self,
        report_id: str,
    ) -> None:

        self.repository.mark_verified(
            report_id,
        )