"use client";

import {
    InvestigationReport,
} from "@/lib/api";

import DomainCard from "./DomainCard";

interface DomainGridProps {
    report: InvestigationReport;
}

export default function DomainGrid({
    report,
}: DomainGridProps) {

    const domains = [

        {
            id: "execution",
            title: "Execution",
            domain: report.execution,
        },

        {
            id: "evidence",
            title: "Evidence",
            domain: report.evidence,
        },

        {
            id: "governance",
            title: "Governance",
            domain: report.governance,
        },

        {
            id: "broker",
            title: "Broker",
            domain: report.broker,
        },

        {
            id: "synchronization",
            title: "Synchronization",
            domain: report.synchronization,
        },

        {
            id: "review",
            title: "Review",
            domain: report.review,
        },

        {
            id: "behavior",
            title: "Behavior",
            domain: report.behavior,
        },

        {
            id: "verification",
            title: "Verification",
            domain: report.verification,
        },

    ];

    const completedDomains = domains.filter(
        ({ domain }) => domain,
    );

    const averageConfidence =
        completedDomains.length > 0
            ? completedDomains.reduce(
                  (sum, { domain }) => sum + domain!.confidence,
                  0,
              ) / completedDomains.length
            : 0;

    return (

        <section className="space-y-4">

            <div>

                <h2 className="text-2xl font-semibold text-slate-900">
                    Institutional Investigation Domains
                </h2>

                <p className="mt-1 text-sm text-slate-500">
                    Canonical investigation domains generated by
                    the Institutional Investigation System.
                </p>

                <div className="mt-6 grid gap-4 md:grid-cols-3">

                    <div className="rounded-lg border bg-white p-4">

                        <div className="text-xs uppercase tracking-wide text-slate-500">

                            Completed Domains

                        </div>

                        <div className="mt-2 text-3xl font-bold">

                            {completedDomains.length}

                        </div>

                    </div>

                    <div className="rounded-lg border bg-white p-4">

                        <div className="text-xs uppercase tracking-wide text-slate-500">

                            Average Confidence

                        </div>

                        <div className="mt-2 text-3xl font-bold">

                            {averageConfidence.toFixed(1)}%

                        </div>

                    </div>

                    <div className="rounded-lg border bg-white p-4">

                        <div className="text-xs uppercase tracking-wide text-slate-500">

                            Investigation Domains

                        </div>

                        <div className="mt-2 text-3xl font-bold">

                            {domains.length}

                        </div>

                    </div>

                </div>

            </div>

            <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">

                {domains.map(({ id, title, domain }) => (

                    <DomainCard

                        key={id}

                        title={title}

                        domain={domain}

                    />

                ))}

            </div>

            <div className="rounded-lg border border-slate-200 bg-slate-50 p-5">

                <div className="text-xs uppercase tracking-wide text-slate-500">

                    Institutional Note

                </div>

                <div className="mt-2 text-sm leading-7 text-slate-700">

                    Every investigation domain is generated independently
                    from the canonical Investigation Context. The Allocator
                    consumes the completed domain outputs to produce the
                    final institutional decision.

                </div>

            </div>

        </section>

    );

}