"use client";

import type {
    InvestigationTimelineEvent,
} from "@/lib/api";

import SectionCard from "../common/SectionCard";

interface Props {

    events: InvestigationTimelineEvent[];

}

function severityStyle(
    severity?: string,
) {

    switch ((severity ?? "").toUpperCase()) {

        case "CRITICAL":

            return "bg-red-100 text-red-800 border-red-300 dark:bg-red-950 dark:text-red-300";

        case "HIGH":

            return "bg-orange-100 text-orange-800 border-orange-300 dark:bg-orange-950 dark:text-orange-300";

        case "MEDIUM":

            return "bg-yellow-100 text-yellow-800 border-yellow-300 dark:bg-yellow-950 dark:text-yellow-300";

        case "LOW":

            return "bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-950 dark:text-blue-300";

        default:

            return "bg-slate-100 text-slate-700 border-slate-300 dark:bg-neutral-800 dark:text-slate-300";

    }

}

export default function TimelinePanel({

    events,

}: Props) {

    return (

        <SectionCard

            title="Investigation Timeline"

            subtitle="Chronological forensic reconstruction generated by the Institutional Investigation System"

        >

            {events.length === 0 ? (

                <div className="rounded-lg border bg-slate-50 dark:bg-neutral-800 p-8">

                    <div className="text-xl font-semibold">

                        No Investigation Timeline Available

                    </div>

                    <div className="mt-4 text-sm text-slate-600 dark:text-slate-400 leading-7">

                        IIS did not reconstruct any chronological investigation
                        events for this workspace.

                    </div>

                    <div className="mt-6 grid gap-3 md:grid-cols-2">

                        <div className="rounded-lg border bg-white dark:bg-neutral-900 p-4">

                            ✓ No audit events recorded

                        </div>

                        <div className="rounded-lg border bg-white dark:bg-neutral-900 p-4">

                            ✓ No synchronization history available

                        </div>

                        <div className="rounded-lg border bg-white dark:bg-neutral-900 p-4">

                            ✓ No review history available

                        </div>

                        <div className="rounded-lg border bg-white dark:bg-neutral-900 p-4">

                            ✓ Timeline generation returned no forensic events

                        </div>

                    </div>

                </div>

            ) : (

                <div
                    className="
                        max-h-[1100px]
                        overflow-y-auto
                        pr-2
                    "
                >

                    <div className="space-y-6">

                    {events.map((event, index) => (

                        <div

                            key={`${event.timestamp}-${event.title}-${index}`}

                            className="flex gap-6"

                        >

                            <div className="flex flex-col items-center">

                                <div

                                    className="
                                        h-5
                                        w-5
                                        rounded-full
                                        bg-blue-600
                                    "

                                />

                                {index !== events.length - 1 && (

                                    <div

                                        className="
                                            mt-2
                                            w-px
                                            flex-1
                                            bg-slate-300
                                            dark:bg-neutral-700
                                        "

                                    />

                                )}

                            </div>

                            <div className="flex-1 rounded-xl border bg-slate-50 dark:bg-neutral-900 p-5">

                                <div className="flex flex-wrap items-start justify-between gap-4">

                                    <div>

                                        <div className="text-xl font-semibold">

                                            {event.title}

                                        </div>

                                        <div className="mt-1 text-sm text-slate-500">

                                            {event.timestamp}

                                        </div>

                                    </div>

                                    <div className="flex flex-wrap gap-2">

                                        <span

                                            className="
                                                rounded-full
                                                border
                                                px-3
                                                py-1
                                                text-xs
                                                uppercase
                                            "

                                        >

                                            {event.category}

                                        </span>

                                        <span

                                            className={`rounded-full border px-3 py-1 text-xs uppercase ${severityStyle(event.severity)}`}

                                        >

                                            {event.severity}

                                        </span>

                                    </div>

                                </div>

                                <div className="mt-5 leading-7 text-slate-700 dark:text-slate-300">

                                    {event.description}

                                </div>

                                {(event.evidence_reference || Object.keys(event.metadata ?? {}).length > 0) && (

                                    <div className="mt-6 space-y-4">

                                        {event.evidence_reference && (

                                            <div className="rounded-lg border bg-white p-4">

                                                <div className="text-xs uppercase tracking-wide text-slate-500">

                                                    Evidence Reference

                                                </div>

                                                <div className="mt-2 font-mono text-sm break-all">

                                                    {event.evidence_reference}

                                                </div>

                                            </div>

                                        )}

                                        {Object.keys(event.metadata ?? {}).length > 0 && (

                                            <div className="rounded-lg border bg-slate-50 p-4">

                                                <div className="mb-3 text-xs font-semibold uppercase tracking-wide text-slate-500">

                                                    Event Metadata

                                                </div>

                                                <div className="grid gap-3 md:grid-cols-2">

                                                    {Object.entries(event.metadata ?? {}).map(
                                                        ([key, value]) => (

                                                            <div
                                                                key={key}
                                                                className="rounded-md bg-white p-3"
                                                            >

                                                                <div className="text-xs uppercase tracking-wide text-slate-500">

                                                                    {key}

                                                                </div>

                                                                <div className="mt-1 font-medium text-slate-800">

                                                                    {String(value)}

                                                                </div>

                                                            </div>

                                                        ),
                                                    )}

                                                </div>

                                            </div>

                                        )}

                                    </div>

                                )}

                            </div>

                        </div>

                    ))}

                </div>

            </div>

            )}

        </SectionCard>

    );

}