from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    DateTime,
    Integer,
    String,
    Text,
    func,
)

from sqlalchemy.dialects.postgresql import JSONB

from sqlalchemy.orm import (
    Mapped,
    mapped_column,
)

from app.core.db import Base


# ==========================================================
# Report Registry
# ==========================================================

class ReportRegistry(Base):
    """
    Canonical registry of every institutional report
    generated by Trading Truth Layer.

    This model stores report metadata only.

    The PDF itself is stored by the Report Registry
    storage layer.
    """

    __tablename__ = "report_registry"

    # ======================================================
    # Identity
    # ======================================================

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    report_id: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        index=True,
        nullable=False,
    )

    report_type: Mapped[str] = mapped_column(
        String(32),
        index=True,
        nullable=False,
    )

    report_title: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    report_version: Mapped[str] = mapped_column(
        String(32),
        default="1.0",
        nullable=False,
    )

    # ======================================================
    # Ownership
    # ======================================================

    workspace_id: Mapped[int] = mapped_column(
        Integer,
        index=True,
        nullable=False,
    )

    claim_id: Mapped[int | None] = mapped_column(
        Integer,
        index=True,
        nullable=True,
    )

    generated_by: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    # ======================================================
    # Lifecycle
    # ======================================================

    status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
    )

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ======================================================
    # Verification
    # ======================================================

    verification_url: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    sha256: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
    )

    # ======================================================
    # Storage
    # ======================================================

    storage_key: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    file_name: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    file_size: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    # ======================================================
    # Download Statistics
    # ======================================================

    download_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )

    last_downloaded_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ======================================================
    # Extensible Metadata
    # ======================================================

    metadata_json: Mapped[dict] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
    )