from __future__ import annotations

"""
Institutional Raw Metadata

RawMetadata represents the synchronization envelope attached to every
piece of broker evidence entering the Universal Evidence Adapter (UEA).

This model contains synchronization, provider, account and transport
information.

It deliberately contains NO trading data.

Trading information belongs inside RawEvidence.

Responsibilities
----------------

• Synchronization identity
• Provider identity
• Broker account identity
• Workspace identity
• Transport identity
• Integrity information
• Synchronization metrics

Every RawEvidence object MUST contain one RawMetadata instance.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


# ============================================================================
# Synchronization Information
# ============================================================================

@dataclass(slots=True)
class SynchronizationInformation:
    """
    Synchronization context generated by the Desktop Trading Engine.
    """

    synchronization_id: str

    synchronization_session: str

    synchronization_batch: str

    synchronization_sequence: int

    synchronization_method: str

    synchronized_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ============================================================================
# Provider Information
# ============================================================================

@dataclass(slots=True)
class ProviderInformation:
    """
    Broker/provider identity.
    """

    provider_name: str

    provider_platform: str

    broker_company: str | None = None

    broker_server: str | None = None

    provider_version: str | None = None


# ============================================================================
# Broker Account Information
# ============================================================================

@dataclass(slots=True)
class BrokerAccountInformation:
    """
    Broker account identity.
    """

    broker_account_id: str

    broker_account_name: str | None = None

    broker_account_type: str | None = None

    account_state: str = "LIVE"

    account_currency: str | None = None

    leverage: str | None = None


# ============================================================================
# Workspace Information
# ============================================================================

@dataclass(slots=True)
class WorkspaceInformation:
    """
    TTL workspace identity.
    """

    workspace_id: int | None = None

    provider_id: str | None = None

    workspace_name: str | None = None

    organization_id: str | None = None


# ============================================================================
# Transport Information
# ============================================================================

@dataclass(slots=True)
class TransportInformation:
    """
    Transport identity.
    """

    transport_version: str = "1.0"

    desktop_engine_version: str | None = None

    payload_hash: str | None = None

    evidence_hash: str | None = None

    payload_size: int | None = None

    encoding: str = "utf-8"


# ============================================================================
# Quality Scores
# ============================================================================

@dataclass(slots=True)
class SynchronizationQuality:
    """
    Synchronization quality metrics.

    These describe the quality of the transport process,
    NOT trading performance.
    """

    integrity_score: float = 100.0

    completeness_score: float = 100.0

    authenticity_score: float = 100.0

    synchronization_score: float = 100.0

    transport_score: float = 100.0

    @property
    def overall_score(self) -> float:
        return (
            self.integrity_score
            + self.completeness_score
            + self.authenticity_score
            + self.synchronization_score
            + self.transport_score
        ) / 5.0


# ============================================================================
# Raw Metadata
# ============================================================================

@dataclass(slots=True)
class RawMetadata:
    """
    Institutional synchronization envelope.

    Every RawEvidence object entering the Universal Evidence Adapter
    carries exactly one RawMetadata object.

    RawMetadata describes HOW the evidence arrived,
    not WHAT the evidence contains.
    """

    synchronization: SynchronizationInformation

    provider: ProviderInformation

    account: BrokerAccountInformation

    workspace: WorkspaceInformation

    transport: TransportInformation

    quality: SynchronizationQuality = field(
        default_factory=SynchronizationQuality
    )

    additional_metadata: dict[str, Any] = field(default_factory=dict)

    received_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def validate(self) -> list[str]:
        """
        Validate metadata integrity.
        """

        issues: list[str] = []

        if not self.provider.provider_name:
            issues.append("Provider name is required.")

        if not self.provider.provider_platform:
            issues.append("Provider platform is required.")

        if not self.account.broker_account_id:
            issues.append("Broker account ID is required.")

        if not self.synchronization.synchronization_id:
            issues.append("Synchronization ID is required.")

        if not self.transport.transport_version:
            issues.append("Transport version is required.")

        return issues

    def to_dict(self) -> dict[str, Any]:
        """
        Export metadata as a dictionary for logging,
        persistence, diagnostics, and auditing.
        """

        return {
            "provider_name": self.provider.provider_name,
            "provider_platform": self.provider.provider_platform,
            "broker_server": self.provider.broker_server,
            "broker_account_id": self.account.broker_account_id,
            "account_state": self.account.account_state,
            "workspace_id": self.workspace.workspace_id,
            "provider_id": self.workspace.provider_id,
            "synchronization_id": self.synchronization.synchronization_id,
            "synchronization_session": self.synchronization.synchronization_session,
            "synchronization_batch": self.synchronization.synchronization_batch,
            "synchronization_sequence": self.synchronization.synchronization_sequence,
            "transport_version": self.transport.transport_version,
            "desktop_engine_version": self.transport.desktop_engine_version,
            "evidence_hash": self.transport.evidence_hash,
            "payload_hash": self.transport.payload_hash,
            "overall_quality_score": self.quality.overall_score,
            "received_at": self.received_at.isoformat(),
        }