from __future__ import annotations

from typing import Any

from app.services.investigations.models import (
    InvestigationReport,
)

from app.services.pdf.common.institutional_sections import (
    build_section_title,
    build_narrative,
)

from app.services.pdf.common.institutional_tables import (
    build_timeline_table,
)


# ==========================================================
# Timeline Reconstruction
# ==========================================================


def build_investigation_timeline(
    story: list[Any],
    report: InvestigationReport,
) -> None:
    """
    Canonical forensic timeline reconstruction.

    Presents the chronological sequence of investigation
    events generated by the Institutional Investigation
    System (IIS).
    """

    story.extend(

        build_section_title(
            "Forensic Timeline Reconstruction",
        )

    )

    story.extend(

        build_narrative(

            [

                (
                    "The forensic timeline reconstructs the complete "
                    "chronological sequence of events observed during "
                    "the institutional investigation."
                ),

                (
                    "Every event is derived from the canonical "
                    "Investigation Context, preserving temporal "
                    "traceability between evidence, findings and the "
                    "allocator decision."
                ),

            ]

        )

    )

    rows = [

        [

            "Timestamp",

            "Category",

            "Severity",

            "Title",

            "Evidence",

        ]

    ]

    for event in report.timeline:

        rows.append(

            [

                str(event.timestamp) if event.timestamp else "-",

                event.category,

                getattr(
                    event.severity,
                    "value",
                    str(event.severity),
                ),

                event.title,

                event.evidence_reference or "-",

            ]

        )

    if len(rows) == 1:

        rows.append(

            [

                "-",

                "-",

                "-",

                "No investigation events available.",

                "-",

            ]

        )

    story.append(

        build_timeline_table(
            rows,
        )

    )

    story.extend(

        build_narrative(

            [

                (
                    f"The investigation reconstructed "
                    f"{len(report.timeline)} chronological event(s)."
                ),

                (
                    "These events establish the temporal foundation "
                    "for evidence correlation, critical-path analysis "
                    "and institutional decision traceability."
                ),

            ]

        )

    )