"use client";

import type {
    InvestigationFinding,
} from "@/lib/api";

import SectionCard
from "../common/SectionCard";

interface Props {

    findings: InvestigationFinding[];

}

interface RoadmapItem {

    priority: number;

    title: string;

    severity: string;

    recommendation: string;

    confidence: number;

}

function priorityValue(
    severity: string,
) {

    switch (severity.toUpperCase()) {

        case "CRITICAL":
            return 1;

        case "HIGH":
            return 2;

        case "MEDIUM":
            return 3;

        case "LOW":
            return 4;

        default:
            return 5;

    }

}

function badgeStyle(
    priority:number,
){

    switch(priority){

        case 1:
            return "bg-red-100 text-red-700";

        case 2:
            return "bg-orange-100 text-orange-700";

        case 3:
            return "bg-amber-100 text-amber-700";

        case 4:
            return "bg-blue-100 text-blue-700";

        default:
            return "bg-slate-100 text-slate-700";

    }

}

export default function FindingRemediationRoadmap({

    findings,

}:Props){

    const roadmap:RoadmapItem[] =

        findings.map(

            finding=>({

                priority:

                    priorityValue(

                        finding.severity,

                    ),

                title:

                    finding.title,

                severity:

                    finding.severity,

                recommendation:

                    finding.recommendation ||

                    "No remediation supplied.",

                confidence:

                    finding.confidence,

            }),

        ).sort(

            (a,b)=>{

                if(

                    a.priority===

                    b.priority

                ){

                    return (

                        b.confidence-

                        a.confidence

                    );

                }

                return (

                    a.priority-

                    b.priority

                );

            },

        );

    return(

        <SectionCard

            title="Institutional Remediation Roadmap"

            subtitle="Recommended order for resolving investigation findings."

        >

            {roadmap.length===0?(

                <div className="rounded-lg border bg-emerald-50 p-6">

                    <div className="text-lg font-semibold text-emerald-700">

                        No Remediation Required

                    </div>

                    <div className="mt-3 leading-7 text-slate-600">

                        IIS did not identify any remediation actions.

                    </div>

                </div>

            ):(

                <div
                    className="
                        max-h-[900px]
                        overflow-y-auto
                        rounded-xl
                        border
                        border-slate-200
                    "
                >

                    <div
                        className="
                            sticky
                            top-0
                            z-10
                            border-b
                            border-slate-200
                            bg-white
                            p-5
                        "
                    >

                        <div className="text-sm font-semibold text-slate-700">

                            Remediation Steps

                        </div>

                        <div className="mt-2 text-sm text-slate-500">

                            Institutional priority order generated by IIS.

                        </div>

                    </div>

                    <div className="space-y-5 p-5">

                        {roadmap.map(

                        (item,index)=>(

                            <div

                                key={`${item.title}-${index}`}

                                className="rounded-xl border bg-white p-6"

                            >

                                <div className="flex items-center justify-between">

                                    <div>

                                        <div className="text-lg font-semibold">

                                            Step {index+1}

                                        </div>

                                        <div className="mt-1 text-slate-700">

                                            {item.title}

                                        </div>

                                    </div>

                                    <span

                                        className={`rounded-full px-3 py-1 text-sm font-semibold ${badgeStyle(item.priority)}`}

                                    >

                                        {item.severity}

                                    </span>

                                </div>

                                <div className="mt-5 leading-7 text-slate-700">

                                    {item.recommendation}

                                </div>

                                <div className="mt-5 flex flex-wrap gap-4 text-sm text-slate-500">

                                    <span>

                                        Confidence:

                                        {" "}

                                        <strong>

                                            {item.confidence.toFixed(1)}%

                                        </strong>

                                    </span>

                                    <span>

                                        Priority:

                                        {" "}

                                        <strong>

                                            {item.priority}

                                        </strong>

                                    </span>

                                </div>

                            </div>

                        ),

                    )}

                </div>

            </div>

            )}

        </SectionCard>

    );

}