"use client";

import type {
    InvestigationRecommendation,
} from "@/lib/api";

import SectionCard from "../common/SectionCard";

interface Props {
    recommendations: InvestigationRecommendation[];
}

function priorityClasses(priority: number): string {

    if (priority >= 90) {
        return "bg-red-100 text-red-700";
    }

    if (priority >= 70) {
        return "bg-orange-100 text-orange-700";
    }

    if (priority >= 40) {
        return "bg-amber-100 text-amber-700";
    }

    return "bg-emerald-100 text-emerald-700";
}

function priorityRank(priority: number): number {

    if (priority >= 90) return 5;

    if (priority >= 70) return 4;

    if (priority >= 40) return 3;

    if (priority >= 20) return 2;

    return 1;

}

export default function RecommendationsTable({
    recommendations,
}: Props) {

    const orderedRecommendations = [...recommendations].sort(

        (a, b) =>

            priorityRank(b.priority) -

            priorityRank(a.priority),

    );

    return (

        <SectionCard
            title="Institutional Recommendations"
            subtitle="Prioritized remediation plan generated by the Institutional Investigation System."
        >

            <div className="grid gap-4 md:grid-cols-4">

                <div className="rounded-lg border bg-slate-50 p-4">

                    <div className="text-xs uppercase tracking-wide text-slate-500">

                        Total

                    </div>

                    <div className="mt-2 text-3xl font-bold">

                        {orderedRecommendations.length}

                    </div>

                </div>

                <div className="rounded-lg border bg-slate-50 p-4">

                    <div className="text-xs uppercase tracking-wide text-slate-500">

                        Automated

                    </div>

                    <div className="mt-2 text-3xl font-bold">

                        {
                            orderedRecommendations.filter(

                                recommendation => recommendation.automated,

                            ).length
                        }

                    </div>

                </div>

                <div className="rounded-lg border bg-slate-50 p-4">

                    <div className="text-xs uppercase tracking-wide text-slate-500">

                        Manual

                    </div>

                    <div className="mt-2 text-3xl font-bold">

                        {
                            orderedRecommendations.filter(

                                recommendation => !recommendation.automated,

                            ).length
                        }

                    </div>

                </div>

                <div className="rounded-lg border bg-slate-50 p-4">

                    <div className="text-xs uppercase tracking-wide text-slate-500">

                        Highest Priority

                    </div>

                    <div className="mt-2 text-3xl font-bold">

                        {orderedRecommendations[0]?.priority ?? "-"}

                    </div>

                </div>

            </div>

            {recommendations.length === 0 ? (

                <div className="rounded-lg border border-dashed border-slate-300 p-6 text-center text-slate-500">

                    No institutional recommendations generated.

                </div>

            ) : (

                <div className="space-y-5">

                    {orderedRecommendations.map((item, index) => (

                        <div
                            key={`${item.title}-${index}`}
                            className="rounded-xl border border-slate-200 bg-white p-5"
                        >

                            <div className="flex items-center justify-between">

                                <div>

                                    <div className="flex items-center gap-3">

                                    <div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 font-semibold">

                                        {index + 1}

                                    </div>

                                    <div className="text-lg font-semibold text-slate-900">

                                        {item.title}

                                    </div>

                                </div>

                                </div>

                                <div className="flex items-center gap-2">

                                    {item.automated && (

                                        <span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700">

                                            Automated

                                        </span>

                                    )}

                                    <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">

                                        {item.priority >= 90
                                            ? "Immediate"

                                            : item.priority >= 70
                                            ? "High"

                                            : item.priority >= 40
                                            ? "Planned"

                                            : "Monitor"}

                                    </span>

                                    <span
                                        className={`rounded-full px-3 py-1 text-xs font-semibold ${priorityClasses(
                                            item.priority,
                                        )}`}
                                    >

                                        Priority {item.priority}

                                    </span>

                                </div>

                            </div>

                            <div className="mt-5">

                                <div className="text-xs uppercase tracking-wide text-slate-500">

                                    Rationale

                                </div>

                                <div className="mt-2 text-sm leading-7 text-slate-700">

                                    {item.rationale || "No rationale provided."}

                                </div>

                            </div>

                            <div className="mt-6">

                                <div className="text-xs uppercase tracking-wide text-slate-500">

                                    Recommended Action

                                </div>

                                <div className="mt-2 text-xs uppercase tracking-wide text-slate-500">

                                    Execution Mode:
                                    {" "}
                                    {item.automated

                                        ? "Automatic remediation available"

                                        : "Manual institutional review required"}

                                </div>

                                <div className="mt-2 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm leading-7 text-slate-800">

                                    {item.action || "No remediation action provided."}

                                </div>

                                <div className="mt-6 rounded-lg bg-slate-50 p-4">

                                    <div className="text-xs uppercase tracking-wide text-slate-500">

                                        Institutional Summary

                                    </div>

                                    <div className="mt-2 leading-7 text-slate-700">

                                        Priority {item.priority} recommendation requiring{" "}

                                        {item.automated
                                            ? "automated"
                                            : "manual"}

                                        {" "}execution.

                                    </div>

                                </div>

                            </div>

                        </div>

                    ))}

                </div>

            )}

        </SectionCard>

    );

}