from __future__ import annotations

"""
Trading Truth Layer
Institutional PDF Design System

This module defines the canonical visual language used by every
institutional PDF generated by Trading Truth Layer.

Responsibilities
----------------
• Brand colour palette
• Page geometry
• Layout spacing tokens
• Table sizing constants
• Typography hierarchy
• Shared paragraph styles
• Backward-compatible aliases

This module intentionally contains NO rendering logic.
Rendering belongs to:

institutional_cover.py
institutional_sections.py
institutional_tables.py
institutional_header_footer.py
institutional_watermark.py
"""

from reportlab.lib import colors
from reportlab.lib.enums import (
    TA_CENTER,
    TA_LEFT,
    TA_RIGHT,
)

from reportlab.lib.styles import (
    ParagraphStyle,
    getSampleStyleSheet,
)

from reportlab.lib.units import inch


# ==========================================================
# DOCUMENT GEOMETRY
# ==========================================================

PAGE_WIDTH = 8.5 * inch
PAGE_HEIGHT = 11 * inch

PAGE_MARGIN = 0.70 * inch

TOP_MARGIN = 0.90 * inch
BOTTOM_MARGIN = 0.75 * inch

HEADER_HEIGHT = 0.75 * inch
FOOTER_HEIGHT = 0.60 * inch

CONTENT_WIDTH = PAGE_WIDTH - (PAGE_MARGIN * 2)

CONTENT_HEIGHT = (
    PAGE_HEIGHT
    - TOP_MARGIN
    - BOTTOM_MARGIN
)

# ==========================================================
# SPACING SCALE
# ==========================================================

SPACE_XXS = 0.05 * inch
SPACE_XS = 0.10 * inch
SPACE_SM = 0.12 * inch
SPACE_MD = 0.18 * inch
SPACE_LG = 0.24 * inch
SPACE_XL = 0.42 * inch
SPACE_XXL = 0.60 * inch

SECTION_TOP_SPACE = SPACE_LG
SECTION_BOTTOM_SPACE = SPACE_SM

TITLE_GAP = SPACE_MD
SUBTITLE_GAP = SPACE_XS
PARAGRAPH_GAP = SPACE_SM
TABLE_GAP = SPACE_MD
QR_GAP = SPACE_LG
LIST_GAP = SPACE_XS

# ==========================================================
# TABLE METRICS
# ==========================================================

TABLE_CELL_PADDING = 10

TABLE_HEADER_PADDING = 12

TABLE_ROW_PADDING = 10

TABLE_BORDER_WIDTH = 0.45

TABLE_GRID_WIDTH = 0.30

TABLE_RADIUS = 0

TABLE_HEADER_HEIGHT = 26

TABLE_ROW_HEIGHT = 22

# ==========================================================
# QR / WATERMARK
# ==========================================================


QR_SIZE = 90

QR_MARGIN = 10

QR_BORDER = 0

WATERMARK_FONT_SIZE = 48

VERIFIED_STAMP_SIZE = 16

# ==========================================================
# FONT SIZES
# ==========================================================

#
# Header
#

HEADER_BRAND_FONT_SIZE = 20

HEADER_SUBTITLE_FONT_SIZE = 10

HEADER_REPORT_FONT_SIZE = 12

HEADER_VERSION_FONT_SIZE = 9

#
# Footer
#

FOOTER_FONT_SIZE = 8

FOOTER_HASH_FONT_SIZE = 7

#
# Watermarks
#

WATERMARK_FONT_SIZE = 48

DRAFT_WATERMARK_FONT_SIZE = 44

CONFIDENTIAL_WATERMARK_FONT_SIZE = 48

DOCUMENT_STATE_FONT_SIZE = 52

VERIFIED_STAMP_FONT_SIZE = 16

HASH_FONT_SIZE = 7

#
# Cover
#

COVER_TITLE_FONT_SIZE = 26

COVER_SUBTITLE_FONT_SIZE = 12

#
# Section
#

SECTION_FONT_SIZE = 16

SUBSECTION_FONT_SIZE = 11

#
# Body
#

BODY_FONT_SIZE = 9

BODY_SMALL_FONT_SIZE = 8

#
# Executive
#

SCORE_FONT_SIZE = 42

VERDICT_FONT_SIZE = 20

BADGE_FONT_SIZE = 10

# ==========================================================
# TABLE TYPOGRAPHY
# ==========================================================

TABLE_FONT_NAME = "Helvetica"

TABLE_HEADER_FONT_NAME = "Helvetica-Bold"

TABLE_FONT_SIZE = 8

TABLE_HEADER_FONT_SIZE = 8

# ==========================================================
# BRAND PALETTE
# ==========================================================

TTL_NAVY = colors.HexColor("#0F172A")

TTL_BLUE = colors.HexColor("#2563EB")

TTL_GREEN = colors.HexColor("#16A34A")

TTL_RED = colors.HexColor("#DC2626")

TTL_ORANGE = colors.HexColor("#EA580C")

TTL_GOLD = colors.HexColor("#C9A227")

TTL_GREY = colors.HexColor("#64748B")

TTL_LIGHT = colors.HexColor("#F8FAFC")

TTL_BORDER = colors.HexColor("#CBD5E1")

TTL_WATERMARK = colors.HexColor("#CBD5E1")

TTL_WHITE = colors.white

TTL_BLACK = colors.black

# ==========================================================
# SEMANTIC COLOURS
# ==========================================================

SUCCESS_COLOUR = TTL_GREEN

WARNING_COLOUR = TTL_ORANGE

CRITICAL_COLOUR = TTL_RED

INFO_COLOUR = TTL_BLUE

PRIMARY_TEXT = TTL_NAVY

SECONDARY_TEXT = TTL_GREY

HEADER_BACKGROUND = TTL_NAVY

HEADER_TEXT = TTL_WHITE

TABLE_HEADER_BACKGROUND = TTL_NAVY

TABLE_HEADER_TEXT = TTL_WHITE

TABLE_ALT_ROW = TTL_LIGHT

TABLE_BORDER = TTL_BORDER

# ==========================================================
# TYPOGRAPHY SPACING (POINTS)
# ==========================================================

#
# ParagraphStyle spacing is measured in points.
#

STYLE_SPACE_NONE = 0

STYLE_SPACE_XXS = 3

STYLE_SPACE_XS = 6

STYLE_SPACE_SM = 8

STYLE_SPACE_MD = 12

STYLE_SPACE_LG = 16

STYLE_SPACE_XL = 20

STYLE_SPACE_XXL = 28

# ==========================================================
# TYPOGRAPHY
# ==========================================================

styles = getSampleStyleSheet()

# ----------------------------------------------------------
# COVER
# ----------------------------------------------------------

COVER_TITLE_STYLE = ParagraphStyle(
    "TTLCoverTitle",
    parent=styles["Heading1"],
    fontName="Helvetica-Bold",
    fontSize=COVER_TITLE_FONT_SIZE,
    leading=30,
    alignment=TA_CENTER,
    textColor=PRIMARY_TEXT,
    spaceAfter=STYLE_SPACE_LG,
)

COVER_SUBTITLE_STYLE = ParagraphStyle(
    "TTLCoverSubtitle",
    parent=styles["Heading2"],
    fontName="Helvetica",
    fontSize=COVER_SUBTITLE_FONT_SIZE,
    leading=16,
    alignment=TA_CENTER,
    textColor=SECONDARY_TEXT,
    spaceAfter=STYLE_SPACE_MD,
)

# ----------------------------------------------------------
# TITLES
# ----------------------------------------------------------

TITLE_STYLE = ParagraphStyle(
    "TTLTitle",
    parent=COVER_TITLE_STYLE,
)

SUBTITLE_STYLE = ParagraphStyle(
    "TTLSubtitle",
    parent=COVER_SUBTITLE_STYLE,
)

SECTION_STYLE = ParagraphStyle(
    "TTLSection",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=SECTION_FONT_SIZE,
    leading=20,
    textColor=PRIMARY_TEXT,
    spaceBefore=4,
    spaceAfter=10,
)

SUBSECTION_STYLE = ParagraphStyle(
    "TTLSubSection",
    parent=styles["Heading3"],
    fontName="Helvetica-Bold",
    fontSize=SUBSECTION_FONT_SIZE,
    leading=14,
    textColor=INFO_COLOUR,
    spaceBefore=2,
    spaceAfter=6,
)

# ----------------------------------------------------------
# EXECUTIVE
# ----------------------------------------------------------

EXECUTIVE_STYLE = ParagraphStyle(
    "TTLExecutive",
    parent=SECTION_STYLE,
    alignment=TA_CENTER,
)

SCORE_STYLE = ParagraphStyle(
    "TTLScore",
    parent=TITLE_STYLE,
    fontName="Helvetica-Bold",
    fontSize=SCORE_FONT_SIZE,
    leading=40,
    alignment=TA_CENTER,
    textColor=INFO_COLOUR,
)

VERDICT_STYLE = ParagraphStyle(
    "TTLVerdict",
    parent=SECTION_STYLE,
    fontName="Helvetica-Bold",
    fontSize=VERDICT_FONT_SIZE,
    leading=24,
    alignment=TA_CENTER,
    textColor=SUCCESS_COLOUR,
)

BADGE_STYLE = ParagraphStyle(
    "TTLBadge",
    parent=styles["BodyText"],
    fontName="Helvetica-Bold",
    fontSize=BADGE_FONT_SIZE,
    leading=12,
    alignment=TA_CENTER,
    textColor=TTL_WHITE,
)

# ----------------------------------------------------------
# BODY
# ----------------------------------------------------------

BODY_STYLE = ParagraphStyle(
    "TTLBody",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=BODY_FONT_SIZE,
    leading=13,
    alignment=TA_LEFT,
    textColor=PRIMARY_TEXT,
)

BODY_SMALL_STYLE = ParagraphStyle(
    "TTLBodySmall",
    parent=BODY_STYLE,
    fontSize=BODY_SMALL_FONT_SIZE,
    leading=11,
)

BODY_CENTER_STYLE = ParagraphStyle(
    "TTLBodyCenter",
    parent=BODY_STYLE,
    alignment=TA_CENTER,
)

BODY_RIGHT_STYLE = ParagraphStyle(
    "TTLBodyRight",
    parent=BODY_STYLE,
    alignment=TA_RIGHT,
)

# ----------------------------------------------------------
# METADATA
# ----------------------------------------------------------

METADATA_STYLE = ParagraphStyle(
    "TTLMetadata",
    parent=BODY_SMALL_STYLE,
    textColor=SECONDARY_TEXT,
)

CAPTION_STYLE = ParagraphStyle(
    "TTLCaption",
    parent=BODY_SMALL_STYLE,
    alignment=TA_CENTER,
    textColor=SECONDARY_TEXT,
)

NOTICE_STYLE = ParagraphStyle(
    "TTLNotice",
    parent=BODY_SMALL_STYLE,
    leading=12,
    textColor=PRIMARY_TEXT,
)

HASH_STYLE = ParagraphStyle(
    "TTLHash",
    parent=BODY_SMALL_STYLE,
    alignment=TA_CENTER,
    textColor=SECONDARY_TEXT,
    fontName="Helvetica",
)

FOOTER_STYLE = ParagraphStyle(
    "TTLFooter",
    parent=BODY_SMALL_STYLE,
    alignment=TA_CENTER,
    textColor=SECONDARY_TEXT,
)

# ----------------------------------------------------------
# SEMANTIC TEXT
# ----------------------------------------------------------

SUCCESS_STYLE = ParagraphStyle(
    "TTLSuccess",
    parent=BODY_STYLE,
    textColor=SUCCESS_COLOUR,
)

WARNING_STYLE = ParagraphStyle(
    "TTLWarning",
    parent=BODY_STYLE,
    textColor=WARNING_COLOUR,
)

ERROR_STYLE = ParagraphStyle(
    "TTLError",
    parent=BODY_STYLE,
    textColor=CRITICAL_COLOUR,
)

INFO_STYLE = ParagraphStyle(
    "TTLInfo",
    parent=BODY_STYLE,
    textColor=INFO_COLOUR,
)

# ==========================================================
# REPORT COMPONENT DIMENSIONS
# ==========================================================

# Executive dashboard
EXECUTIVE_CARD_HEIGHT = 0.55 * inch

EXECUTIVE_CARD_PADDING = 10

# Score presentation
SCORE_BOX_HEIGHT = 0.90 * inch

SCORE_BOX_WIDTH = 2.20 * inch

# Verification badge
BADGE_HEIGHT = 0.34 * inch

BADGE_PADDING = 6

# Cover
COVER_TOP_SPACING = 0.80 * inch

COVER_SECTION_SPACING = 0.32 * inch

# ==========================================================
# TABLE COLUMN WIDTHS
# ==========================================================

TABLE_COL_SMALL = 0.90 * inch

TABLE_COL_MEDIUM = 1.50 * inch

TABLE_COL_LARGE = 2.40 * inch

TABLE_COL_XL = 3.20 * inch

# ==========================================================
# BULLET SETTINGS
# ==========================================================

BULLET_CHARACTER = "•"

BULLET_INDENT = 12

# ==========================================================
# WATERMARK
# ==========================================================

WATERMARK_ROTATION = 30

WATERMARK_OPACITY = 0.20

# ==========================================================
# STATUS COLOURS
# ==========================================================

STATUS_COLOURS = {

    "verified": SUCCESS_COLOUR,

    "approved": SUCCESS_COLOUR,

    "valid": SUCCESS_COLOUR,

    "passed": SUCCESS_COLOUR,

    "review": WARNING_COLOUR,

    "monitoring": WARNING_COLOUR,

    "warning": WARNING_COLOUR,

    "high review": WARNING_COLOUR,

    "failed": CRITICAL_COLOUR,

    "rejected": CRITICAL_COLOUR,

    "compromised": CRITICAL_COLOUR,

    "critical": CRITICAL_COLOUR,

}

# ==========================================================
# COMPATIBILITY ALIASES
# ==========================================================

#
# Existing reports currently import these names.
# They are intentionally preserved so every current
# report continues to work without modification.
#

SMALL_STYLE = BODY_SMALL_STYLE

CENTER_STYLE = BODY_CENTER_STYLE

RIGHT_STYLE = BODY_RIGHT_STYLE

# Existing spacing names

TITLE_GAP = SPACE_MD

SUBTITLE_GAP = SPACE_XS

TABLE_GAP = SPACE_MD

PARAGRAPH_GAP = SPACE_SM

QR_GAP = SPACE_LG

# Existing colours

TTL_SUCCESS = SUCCESS_COLOUR

TTL_WARNING = WARNING_COLOUR

TTL_ERROR = CRITICAL_COLOUR

TTL_INFO = INFO_COLOUR

# ==========================================================
# EXPORTS
# ==========================================================

__all__ = [

    #
    # Layout
    #

    "PAGE_WIDTH",
    "PAGE_HEIGHT",

    "PAGE_MARGIN",

    "TOP_MARGIN",
    "BOTTOM_MARGIN",

    "HEADER_HEIGHT",
    "FOOTER_HEIGHT",

    "CONTENT_WIDTH",
    "CONTENT_HEIGHT",

    #
    # Spacing
    #

    "SPACE_XXS",
    "SPACE_XS",
    "SPACE_SM",
    "SPACE_MD",
    "SPACE_LG",
    "SPACE_XL",
    "SPACE_XXL",

    "SECTION_TOP_SPACE",
    "SECTION_BOTTOM_SPACE",

    #
    # Colours
    #

    "TTL_NAVY",
    "TTL_BLUE",
    "TTL_GREEN",
    "TTL_RED",
    "TTL_ORANGE",
    "TTL_GOLD",
    "TTL_GREY",
    "TTL_LIGHT",
    "TTL_BORDER",
    "TTL_WATERMARK",
    "TTL_WHITE",
    "TTL_BLACK",

    #
    # Styles
    #

    "TITLE_STYLE",
    "SUBTITLE_STYLE",
    "SECTION_STYLE",
    "SUBSECTION_STYLE",

    "BODY_STYLE",
    "BODY_SMALL_STYLE",
    "BODY_CENTER_STYLE",
    "BODY_RIGHT_STYLE",

    "NOTICE_STYLE",
    "CAPTION_STYLE",
    "METADATA_STYLE",
    "HASH_STYLE",

    "SUCCESS_STYLE",
    "WARNING_STYLE",
    "ERROR_STYLE",
    "INFO_STYLE",

    "SCORE_STYLE",
    "VERDICT_STYLE",
    "BADGE_STYLE",

    #
    # Compatibility
    #

    "SMALL_STYLE",
    "CENTER_STYLE",
    "RIGHT_STYLE",

    #
    # Misc
    #

    "QR_SIZE",

    "WATERMARK_FONT_SIZE",

    "WATERMARK_ROTATION",

    "WATERMARK_OPACITY",

    "STATUS_COLOURS",

]