"""add ingestion sessions

Revision ID: 4825d52fd6de
Revises: 
Create Date: 2026-05-09 21:51:27.696221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4825d52fd6de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_tag_map')
    op.drop_index(op.f('ix_trade_tags_id'), table_name='trade_tags')
    op.drop_index(op.f('ix_trade_tags_name'), table_name='trade_tags')
    op.drop_index(op.f('ix_trade_tags_workspace_id'), table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_table('playing_with_neon')
    op.drop_column('workspaces', 'lemon_product_id')
    op.drop_column('workspaces', 'subscription_source')
    op.drop_column('workspaces', 'lemon_variant_id')
    op.drop_column('workspaces', 'lemon_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('lemon_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('lemon_variant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('subscription_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('lemon_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.create_table('trade_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_tags_pkey'))
    )
    op.create_index(op.f('ix_trade_tags_workspace_id'), 'trade_tags', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_trade_tags_name'), 'trade_tags', ['name'], unique=False)
    op.create_index(op.f('ix_trade_tags_id'), 'trade_tags', ['id'], unique=False)
    op.create_table('trade_tag_map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['trade_tags.id'], name=op.f('trade_tag_map_tag_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('trade_tag_map_trade_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_tag_map_pkey'))
    )
    # ### end Alembic commands ###
