"""
Trading Truth Layer

Volume IV

Institutional Capital Allocation Infrastructure

Domain VI

Institutional Investigation Infrastructure
(Investigation Center)
"""

from reportlab.platypus import (
    Paragraph,
    Spacer,
    PageBreak,
)

from app.services.pdf.common.institutional_theme import (
    TITLE_STYLE,
    SUBTITLE_STYLE,
    BODY_STYLE,
    BODY_CENTER_STYLE,
    SPACE_MD,
    SPACE_LG,
)



# ==========================================================
# PUBLIC API
# ==========================================================


def build_domain_6_investigation_center():

    """
    Builds Domain VI.

    Institutional Investigation Infrastructure.
    """

    story = []

    # --------------------------------------------------
    # DOMAIN TITLE
    # --------------------------------------------------

    story.append(
        Paragraph(
            "DOMAIN VI",
            TITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION INFRASTRUCTURE",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Paragraph(
            "(INVESTIGATION CENTER)",
            BODY_CENTER_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL POSITIONING
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION INFRASTRUCTURE",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Institutional Investigation Infrastructure "
            "serves as the institutional due diligence and "
            "allocator reasoning layer of Trading Truth Layer.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "It performs institutional investigations across "
            "canonical evidence, verification records, governance "
            "artifacts and trust intelligence to determine whether "
            "institutional capital allocation decisions can be "
            "supported.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Every institutional investigation is generated by "
            "the Institutional Investigation System (IIS), which "
            "produces allocator-ready intelligence, residual risk "
            "assessments and institutional recommendations.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # PRIMARY RESPONSIBILITIES
    # --------------------------------------------------

    story.append(
        Paragraph(
            "PRIMARY RESPONSIBILITIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    responsibilities = [

        "Institutional investigations.",

        "Allocator reasoning.",

        "Residual risk assessment.",

        "Institutional findings generation.",

        "Cross-domain intelligence analysis.",

        "Institutional recommendations.",

        "Allocator decision production.",

        "Forensic investigation reporting.",

        "Institutional due diligence automation.",

        "Institutional capital allocation readiness.",

    ]

    for responsibility in responsibilities:

        story.append(
            Paragraph(
                f"• {responsibility}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL SUBDOMAINS
    # --------------------------------------------------

    story.append(PageBreak())

    story.append(
        Paragraph(
            "INSTITUTIONAL SUBDOMAINS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    subdomains = [

        "Investigation Overview.",

        "Investigation Timeline.",

        "Investigation Evidence.",

        "Institutional Investigation Domains.",

        "Institutional Investigation Findings.",

        "Institutional Investigation Report Center.",

    ]

    for subdomain in subdomains:

        story.append(
            Paragraph(
                f"• {subdomain}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

        # --------------------------------------------------
    # INVESTIGATION OVERVIEW
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INVESTIGATION OVERVIEW",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Investigation Overview page serves as the "
            "executive command surface of the Institutional "
            "Investigation System (IIS).",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "It exposes allocator readiness, institutional "
            "confidence, domain health, residual risk, findings "
            "and the final institutional allocator decision "
            "generated by IIS.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "The Investigation Overview page acts as the "
            "canonical allocator readiness surface of the "
            "Institutional Investigation Infrastructure.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL QUESTIONS ANSWERED
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL QUESTIONS ANSWERED",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    questions = [

        "Has the institutional investigation completed successfully?",

        "Can the allocator decision be institutionally relied upon?",

        "What institutional confidence score was assigned?",

        "Which investigation domains contributed to the allocator decision?",

        "What institutional risks have been identified?",

        "Is the workspace allocator-ready?",

        "Which institutional findings require remediation?",

        "What is the final institutional recommendation?",

    ]

    for question in questions:

        story.append(
            Paragraph(
                f"• {question}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL INVESTIGATION SYSTEM (IIS)
    # --------------------------------------------------

    story.append(PageBreak())

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION SYSTEM (IIS)",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Investigation Overview page is powered entirely "
            "by the Institutional Investigation System (IIS).",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "The IIS performs institutional reasoning across "
            "multiple investigation domains before producing "
            "allocator-ready intelligence and institutional "
            "recommendations.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    iis_outputs = [

        "Canonical investigation metadata.",

        "Institutional investigation confidence scores.",

        "Institutional allocator decisions.",

        "Residual risk assessments.",

        "Institutional findings.",

        "Institutional recommendations.",

        "Domain health assessments.",

        "Coverage metrics.",

        "Institutional summaries.",

    ]

    for output in iis_outputs:

        story.append(
            Paragraph(
                f"• {output}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL INVESTIGATION STATUS
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION STATUS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    status_metrics = [

        "Investigation Status.",

        "Investigation Confidence.",

        "Domains Completed.",

        "Institutional Findings.",

        "Allocator Decision.",

    ]

    for metric in status_metrics:

        story.append(
            Paragraph(
                f"• {metric}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    investigation_statuses = [

        "COMPLETE",

        "RUNNING",

        "PENDING",

        "FAILED",

    ]

    story.append(
        Paragraph(
            "Possible investigation statuses include:",
            BODY_STYLE,
        )
    )

    for status in investigation_statuses:

        story.append(
            Paragraph(
                f"• {status}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    allocator_decisions = [

        "ACCEPT",

        "CONDITIONAL_ACCEPT",

        "REJECT",

        "REVIEW_REQUIRED",

    ]

    story.append(PageBreak())

    story.append(
        Paragraph(
            "Possible allocator decisions include:",
            BODY_STYLE,
        )
    )

    for decision in allocator_decisions:

        story.append(
            Paragraph(
                f"• {decision}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INVESTIGATION PROVENANCE
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INVESTIGATION PROVENANCE",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    provenance_metadata = [

        "Decision Engine.",

        "Allocator Engine.",

        "Investigation Domains.",

        "Investigation Confidence.",

        "Institutional Decision.",

        "Residual Risk.",

        "Evidence Nodes.",

        "Relationships.",

        "Institutional Findings.",

        "Recommendations.",

        "Timeline Events.",

        "Generated Timestamp.",

    ]

    for item in provenance_metadata:

        story.append(
            Paragraph(
                f"• {item}",
                BODY_STYLE,
            )
        )

    story.append(
        Paragraph(
            "Investigation provenance provides complete allocator "
            "transparency regarding how institutional decisions "
            "were produced by the Investigation System.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL INVESTIGATION PIPELINE
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION PIPELINE",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    pipeline_metrics = [

        "Investigation Stage.",

        "Completed Domains.",

        "Evidence Coverage.",

        "Institutional Findings.",

        "Recommendations.",

        "Allocator Status.",

        "Runtime Status.",

    ]

    for metric in pipeline_metrics:

        story.append(
            Paragraph(
                f"• {metric}",
                BODY_STYLE,
            )
        )

    story.append(
        Paragraph(
            "The Investigation Pipeline communicates the allocator "
            "readiness of the completed institutional investigation.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

        # --------------------------------------------------
    # INVESTIGATION TIMELINE
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INVESTIGATION TIMELINE",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Investigation Timeline provides a complete "
            "institutional audit trail of every event generated "
            "throughout the Institutional Investigation workflow.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "The timeline preserves the chronological progression "
            "of allocator reasoning, findings generation and "
            "institutional recommendations.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Institutional allocators may therefore understand "
            "how the Investigation System arrived at its final "
            "allocator decision.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # TIMELINE CAPABILITIES
    # --------------------------------------------------

    story.append(
        Paragraph(
            "TIMELINE CAPABILITIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    timeline_capabilities = [

        "Investigation stage tracking.",

        "Institutional findings tracking.",

        "Allocator decision tracking.",

        "Residual risk tracking.",

        "Recommendation tracking.",

        "Institutional review tracking.",

        "Cross-domain investigation tracking.",

    ]

    for capability in timeline_capabilities:

        story.append(
            Paragraph(
                f"• {capability}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INVESTIGATION EVIDENCE
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INVESTIGATION EVIDENCE",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Investigation Evidence subsystem preserves the "
            "institutional evidence utilized throughout allocator "
            "due diligence workflows.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Evidence is collected across all institutional "
            "domains operating inside Trading Truth Layer and "
            "consolidated into a single institutional review "
            "surface.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Investigation Evidence establishes the institutional "
            "foundation required to support allocator decisions.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # EVIDENCE RESPONSIBILITIES
    # --------------------------------------------------

    story.append(
        Paragraph(
            "EVIDENCE RESPONSIBILITIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    evidence_responsibilities = [

        "Institutional evidence aggregation.",

        "Evidence provenance tracking.",

        "Cross-domain evidence analysis.",

        "Residual risk assessment.",

        "Allocator evidence presentation.",

        "Institutional evidence exports.",

    ]

    for responsibility in evidence_responsibilities:

        story.append(
            Paragraph(
                f"• {responsibility}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INVESTIGATION DOMAINS
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION DOMAINS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Institutional Investigation System performs "
            "institutional reasoning across multiple investigation "
            "domains before producing allocator-grade decisions.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Each investigation domain is independently assessed "
            "before contributing to the overall institutional "
            "confidence score.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    investigation_domains = [

        "Evidence Domain.",

        "Verification Domain.",

        "Governance Domain.",

        "Behavior Domain.",

        "Capital Domain.",

        "Broker Domain.",

        "Allocator Domain.",

        "Synchronization Domain.",

        "Critical Path Domain.",

        "Review Domain.",

        "Compliance Domain.",

    ]

    for domain in investigation_domains:

        story.append(
            Paragraph(
                f"• {domain}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # DOMAIN RESPONSIBILITIES
    # --------------------------------------------------

    story.append(PageBreak())

    story.append(
        Paragraph(
            "DOMAIN RESPONSIBILITIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    domain_responsibilities = [

        "Institutional evidence assessment.",

        "Verification maturity assessment.",

        "Institutional governance assessment.",

        "Residual risk assessment.",

        "Allocator confidence assessment.",

        "Institutional recommendation generation.",

    ]

    for responsibility in domain_responsibilities:

        story.append(
            Paragraph(
                f"• {responsibility}",
                BODY_STYLE,
            )
        )

    story.append(
        Paragraph(
            "Collectively, the investigation domains establish "
            "the institutional reasoning capabilities of the "
            "Institutional Investigation System.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

        # --------------------------------------------------
    # INSTITUTIONAL INVESTIGATION FINDINGS
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION FINDINGS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "Institutional Findings represent the formal conclusions "
            "produced by the Institutional Investigation System "
            "following allocator-grade due diligence procedures.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Findings are generated from cross-domain investigation "
            "results and provide institutions with actionable "
            "allocator intelligence.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Every finding is institutionally traceable and linked "
            "to the underlying evidence and investigation domains "
            "which contributed to its production.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # FINDING CATEGORIES
    # --------------------------------------------------

    story.append(
        Paragraph(
            "FINDING CATEGORIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    finding_categories = [

        "Verification Findings.",

        "Evidence Findings.",

        "Integrity Findings.",

        "Governance Findings.",

        "Risk Findings.",

        "Allocator Findings.",

        "Compliance Findings.",

        "Institutional Recommendations.",

    ]

    for category in finding_categories:

        story.append(
            Paragraph(
                f"• {category}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # RESIDUAL RISK ASSESSMENTS
    # --------------------------------------------------

    story.append(
        Paragraph(
            "RESIDUAL RISK ASSESSMENTS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "Residual Risk Assessments quantify the institutional "
            "risks that remain following completion of the "
            "investigation workflow.",
            BODY_STYLE,
        )
    )

    residual_risks = [

        "Verification Risk.",

        "Evidence Risk.",

        "Governance Risk.",

        "Integrity Risk.",

        "Allocator Risk.",

        "Operational Risk.",

        "Institutional Trust Risk.",

    ]

    for risk in residual_risks:

        story.append(
            Paragraph(
                f"• {risk}",
                BODY_STYLE,
            )
        )

    story.append(
       Paragraph(
            "Residual risk intelligence forms a critical component "
            "of institutional capital allocation decisions.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL RECOMMENDATIONS
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL RECOMMENDATIONS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    recommendations = [

        "Accept.",

        "Conditional Accept.",

        "Further Review Required.",

        "Reject.",

        "Remediation Required.",

        "Allocator Review Required.",

    ]

    for recommendation in recommendations:

        story.append(
            Paragraph(
                f"• {recommendation}",
                BODY_STYLE,
            )
        )

    story.append(
        Paragraph(
            "Institutional recommendations communicate the "
            "allocator readiness posture of the investigated "
            "verification records.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INVESTIGATION REPORT CENTER
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL INVESTIGATION REPORT CENTER",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Institutional Investigation Report Center provides "
            "allocator-grade investigation reporting capabilities "
            "across all IIS investigation domains.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Institutional reports consolidate investigation "
            "findings, allocator decisions, residual risk "
            "assessments and recommendations into a single "
            "institutional due diligence artifact.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # REPORTING RESPONSIBILITIES
    # --------------------------------------------------

    story.append(
        Paragraph(
            "REPORTING RESPONSIBILITIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    reporting_responsibilities = [

        "Institutional Investigation Reports.",

        "Allocator Reports.",

        "Institutional Due Diligence Reports.",

        "Residual Risk Reports.",

        "Institutional Findings Reports.",

        "Institutional Recommendation Reports.",

    ]

    for responsibility in reporting_responsibilities:

        story.append(
            Paragraph(
                f"• {responsibility}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INVESTIGATION WORKFLOW POSITION
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INVESTIGATION WORKFLOW POSITION",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    workflow = [

        "Canonical Evidence Infrastructure",

        "Claim Governance Infrastructure",

        "Trust Intelligence Infrastructure",

        "Institutional Investigation Infrastructure",

        "Public Trust Infrastructure",

    ]

    for item in workflow:

        story.append(
            Paragraph(
                item,
                BODY_CENTER_STYLE,
            )
        )

        story.append(
            Spacer(
                1,
                SPACE_MD,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL QUESTIONS ANSWERED
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL QUESTIONS ANSWERED",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    questions = [

        "Can institutional capital be allocated confidently?",

        "What residual risks remain?",

        "What institutional findings were identified?",

        "Which investigation domains contributed to the decision?",

        "What allocator recommendation was produced?",

        "Is remediation required?",

        "Has institutional due diligence been completed?",

        "Is the claim allocator-ready?",

    ]

    for question in questions:

        story.append(
            Paragraph(
                f"• {question}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # FUTURE INFRASTRUCTURE CAPABILITIES
    # --------------------------------------------------

    story.append(
        Paragraph(
            "FUTURE INFRASTRUCTURE CAPABILITIES",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    future_capabilities = [

        "Automated allocator reasoning.",

        "Cross-workspace investigations.",

        "Institutional benchmark investigations.",

        "Advanced residual risk intelligence.",

        "Institutional remediation workflows.",

        "Institutional allocation intelligence.",

        "Multi-layer due diligence automation.",

    ]

    for capability in future_capabilities:

        story.append(
            Paragraph(
                f"• {capability}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # ARCHITECTURE SUMMARY
    # --------------------------------------------------

    story.append(
        Paragraph(
            "ARCHITECTURE SUMMARY",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Institutional Investigation Infrastructure "
            "represents the allocator reasoning layer of Trading "
            "Truth Layer.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "It performs institutional due diligence across all "
            "verification domains and produces allocator-grade "
            "intelligence required for evidence-based capital "
            "allocation decisions.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "The Institutional Investigation System enables "
            "institutions to move beyond verification into "
            "allocator-ready institutional decision making.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

        # --------------------------------------------------
    # DOMAIN VI ARCHITECTURE STATUS
    # --------------------------------------------------

    story.append(
        Paragraph(
            "DOMAIN VI ARCHITECTURE STATUS",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    architecture_components = [

        "Investigation Overview.",

        "Investigation Timeline.",

        "Investigation Evidence.",

        "Institutional Investigation Domains.",

        "Institutional Investigation Findings.",

        "Institutional Investigation Report Center.",

    ]

    for component in architecture_components:

        story.append(
            Paragraph(
                f"• {component}",
                BODY_STYLE,
            )
        )

    story.append(
        Paragraph(
            "These institutional capabilities collectively "
            "establish the Institutional Investigation "
            "Infrastructure of Trading Truth Layer.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # INSTITUTIONAL POSITIONING
    # --------------------------------------------------

    story.append(
        Paragraph(
            "INSTITUTIONAL POSITIONING",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    story.append(
        Paragraph(
            "The Institutional Investigation Infrastructure is "
            "positioned immediately after the Trust Intelligence "
            "Infrastructure within the TTL institutional trust "
            "lifecycle.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Its responsibility is not to verify evidence or "
            "compute trust metrics. Its responsibility is to "
            "perform allocator-grade institutional investigations "
            "using all intelligence produced throughout the TTL "
            "ecosystem.",
            BODY_STYLE,
        )
    )

    story.append(
        Paragraph(
            "Institutional investigations therefore represent the "
            "final due diligence layer before public trust "
            "distribution and institutional capital allocation "
            "decisions are made.",
            BODY_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # DOMAIN SUMMARY
    # --------------------------------------------------

    story.append(
        Paragraph(
            "DOMAIN SUMMARY",
            SUBTITLE_STYLE,
        )
    )

    story.append(
        Spacer(
            1,
            SPACE_MD,
        )
    )

    summary_points = [

        "Consumes institutional evidence and trust intelligence.",

        "Performs allocator-grade institutional investigations.",

        "Produces residual risk assessments and findings.",

        "Generates institutional recommendations.",

        "Produces allocator-ready due diligence reports.",

        "Supports evidence-based capital allocation decisions.",

        "Acts as the institutional reasoning layer of Trading Truth Layer.",

    ]

    for point in summary_points:

        story.append(
            Paragraph(
                f"• {point}",
                BODY_STYLE,
            )
        )

    story.append(
        Spacer(
            1,
            SPACE_LG,
        )
    )

    # --------------------------------------------------
    # PAGE BREAK
    # --------------------------------------------------

    story.append(
        PageBreak()
    )

    return story


# ==========================================================
# END OF FILE
# ==========================================================